### ISSUE TITLE
ESLint with Coffee

### ISSUE THREAD

**Issue by MentalGear** [cxsper/vue-cli-plugin-coffee#3]
Source: https://quasar.dev/quasar-cli/cli-documentation/handling-webpack#Coffeescript

> Tell ESLint which Vue components are using Coffeescript.
> 
> Note that vue-loader uses lang="coffee" to identify components which are using Coffeescript, but lang="coffee" is not recognizable for ESLint. Fortunately, ESLint (following traditional HTML) uses type="xxx" to identify the type of scripts. As long as a <script> tag has any type other than javascript, ESLint would mark the script as non-javascript, and skips linting it. Coffeescript’s convention is to use type="text/coffeescript" to identify itself. Therefore, in your Vue components which are using Coffeescript, using both lang and type to avoid ESLint warnings.

Maybe add to the readme ?

**Comment by cxsper** [comment]
@MentalGear thank you, I will
