### ISSUE TITLE
Include babel loader

### ISSUE THREAD

**Issue by phil294** [cxsper/vue-cli-plugin-coffee#4]
Hi!
Contrary to https://github.com/thisredone/vue-cli-plugin-coffeescript/blob/f67679bfd1eca5e1c0cd81a8831c298739620a0e/index.js#L17, this plugin does not include the babel loader. This is really unfortunate, if you are relying on `babel.config.js`, `.browserlistrc` or the like, as suggested by the official docs.
So maybe this should be adjusted?

Shouldnt this repo be a mere fork of the other plugin anyway?
Thanks

**Comment by cxsper** [comment]
I see why you are asking but also I don't see why should anything be included beside coffeescript loader.

Also I don't see any babel-loader as a peerDependency here: https://github.com/thisredone/vue-cli-plugin-coffeescript/blob/f67679bfd1eca5e1c0cd81a8831c298739620a0e/package.json
Not sure about the assumption that every coffeescript project has babel-loader wired in it.

I will consider adding this based on checking whether the babel is present in the setup.

I will consider the same for ESLint and cache-loader.

About a mere fork - yes, it should've been but it wasn't the case. I simply didn't found that repo at the time I was making this plugin. It was created several days before mine. And after I made this plugin I saw that repo and mentioned it in README.md

Of course it would be easier to fork the repo, remove main.coffee searching, remove babel and whatever I wanted to do, but it just wasn't the case.

**Comment by cxsper** [comment]
Now the whole plugin has just been re-written and does a lot more than before.
Closing this

But including babel by default seems strange to me. Instead i am checking if one has this plugin right now. And then I require babel-loader as a peer-dependency

**Comment by phil294** [comment]
I think it makes sense to provide babel functionality somehow since the coffeescript CLI also has a [`--transpile` option](https://coffeescript.org/#transpilation).

You are right that including it by default is not the best idea. This optional inclusion https://github.com/cxspxr/vue-cli-plugin-coffee/blob/635e5dc6c5f1e2dd13e4164555a87ee698475f26/index.js#L22-L24 seems like the perfect solution, nice!

Besides, according to [coffee-loader docs](https://github.com/webpack-contrib/coffee-loader#coffeescript-and-babel), it seems that instead of using babel-loader, you could also make coffee-loader do that for you instead with `coffee-loader.options.transpile.presets = ['@babel/env']`, but I dont really see the point in that, you wouldnt be referring to `babel.config.js` anymore etc
